[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.20"
optimizer = true
optimizer_runs = 1000000

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

